# Generated by Django 3.2.16 on 2022-10-31 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dataTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 18, 23, 24, 961943)),
        ),
    ]
