# Generated by Django 3.2.16 on 2022-11-06 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comments_datatime'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dataTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 23, 29, 45, 134430)),
        ),
    ]
