# Generated by Django 3.2.16 on 2022-10-28 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221028_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dataTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 13, 51, 24, 435375)),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Followeing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Followers',
            field=models.IntegerField(default=0),
        ),
    ]
