# Generated by Django 3.2.16 on 2022-10-29 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221028_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dataTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 15, 48, 29, 702464)),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
